services:
  - type: web
    name: daily-questions-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DBNAME
        value: daily_questions
      - key: FIREBASE_CREDENTIALS_PATH
        value: app/dailyquestion-fcbae-firebase-adminsdk-fbsvc-282e703108.json
      - key: RESEND_API_KEY
        sync: false
      - key: REMINDER_TIME
        value: 20:00
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/health

